#!/usr/bin/env python3
"""Tabulate LN-Recal's selection sweep, so the cells the rule did *not* pick are visible.

The declared rule (``selection:RidgeGrid``) minimizes paired distance harm, which is a
choice that biases toward a smaller correction. Publishing only the winner would hide
what the other seven cells did -- including what a success-scored rule would have picked
-- so this script reads the cached selection columns the sweep already produced and writes
the whole grid.

Nothing here is part of the submission path: it reads ``eval_outputs/`` and prints a table.

    .venv/bin/python methods/ln_recal/sweep_table.py --settings pushobj pusht \
        > methods/ln_recal/SWEEP.md
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

from paarbench import metrics  # noqa: E402
from paarbench.schema import load_column  # noqa: E402

METHOD = "ln_recal"


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--settings", nargs="+", default=["pushobj"],
                    help="settings whose selection sweep ran (pushobj_shift has none)")
    ap.add_argument("--out-root", type=Path, default=REPO_ROOT / "eval_outputs")
    return ap.parse_args()


def cells(out_root: Path, setting: str):
    """Every ``<method>/select<NN>`` column the selection sweep left on disk."""
    root = out_root / METHOD
    for select_dir in sorted(root.glob("select*")):
        column = select_dir / setting / "selection"
        summary = column / "column_summary.json"
        if not summary.is_file():
            continue
        record = json.loads(summary.read_text())
        yield select_dir.name, record, column


def main() -> int:
    args = parse_args()
    print("# LN-Recal selection sweep\n")
    print("Generated by `methods/ln_recal/sweep_table.py --settings "
          f"{' '.join(args.settings)}` from the cached selection columns. **Selection cohort "
          "only** — none of these numbers is a benchmark result; the reported result is in "
          "`LEADERBOARD.md`. `pushobj_shift` has no selection cohort and therefore no "
          "sweep: it is evaluated with what was frozen on `pushobj`.\n")
    for setting in args.settings:
        render(setting, args.out_root)
    return 0


def render(setting: str, out_root: Path) -> None:
    args = argparse.Namespace(setting=setting, out_root=out_root)
    frozen_column = args.out_root / "frozen" / args.setting / "selection"
    frozen_frame = (load_column(frozen_column, "frozen", args.setting, "selection")
                    if frozen_column.is_dir() else pd.DataFrame())
    if frozen_frame.empty:
        print(f"no frozen selection column under {frozen_column}; paired columns will be "
              f"blank", file=sys.stderr)

    rows = []
    for name, record, column in cells(args.out_root, args.setting):
        frame = load_column(column, METHOD, args.setting, "selection")
        summary = {}
        if not frame.empty and not frozen_frame.empty:
            summary = metrics.summarize(
                pd.concat([frame, frozen_frame], ignore_index=True), METHOD, args.setting
            )
        params = record.get("params", {})
        distance = (summary.get("distance") or {}).get("median_paired_delta")
        catastrophe = (summary.get("catastrophe") or {}).get("catastrophe_rate")
        compounding = (summary.get("compounding") or {}).get("slope_per_replan")
        rows.append({
            "cell": name,
            "fit_weight": params.get("fit_weight"),
            "ridge": params.get("ridge"),
            "success": record.get("success"),
            "median dist Δ": distance,
            "catastrophe": catastrophe,
            "compounding": compounding,
            "delta_rms_rel": _median_metric(column, "ln_recal/delta_rms_rel"),
            "fit_residual_ratio": _median_metric(column, "ln_recal/fit_residual_ratio"),
        })

    rows.sort(key=lambda r: (bool(r["fit_weight"]), r["ridge"] or 0))
    frozen_success = _column_success(frozen_column)

    print(f"## `{args.setting}` selection cohort\n")
    if frozen_success is not None:
        print(f"Frozen reference on this cohort, run by the harness in the same evaluation "
              f"mode: **{frozen_success:.3f}**.\n")
    print("| fit_weight | ridge | success | median dist Δ | catastrophe | compounding | "
          "delta_rms_rel | fit_residual_ratio |")
    print("|---|---|---|---|---|---|---|---|")
    for r in rows:
        print(f"| {str(r['fit_weight']).lower()} | {r['ridge']:g} | "
              f"{_fmt(r['success'], 3)} | {_fmt(r['median dist Δ'], 0, sign=True)} | "
              f"{_pct(r['catastrophe'])} | {_fmt(r['compounding'], 2, sign=True)} | "
              f"{_fmt(r['delta_rms_rel'], 4)} | {_fmt(r['fit_residual_ratio'], 3)} |")
    print()
    print("`delta_rms_rel` and `fit_residual_ratio` are medians over every replan of the "
          "column: the size of the emitted correction relative to the affine it perturbs, "
          "and the one-step latent error after the fit over the error before it.\n")


def _fmt(value, places: int, sign: bool = False) -> str:
    if value is None:
        return "—"
    return f"{value:{'+' if sign else ''}.{places}f}"


def _pct(value) -> str:
    return "—" if value is None else f"{value:.1%}"


def _column_success(column: Path):
    summary = column / "column_summary.json"
    if not summary.is_file():
        return None
    return json.loads(summary.read_text()).get("success")


def _median_metric(column: Path, key: str):
    """Median of a per-replan adapter metric across every unit of a column."""
    values = []
    for logs in sorted(column.glob("*/logs.json")):
        for line in logs.read_text().splitlines():
            if not line.strip():
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                continue
            if key in row:
                values.append(float(row[key]))
    if not values:
        return None
    return float(pd.Series(values).median())


if __name__ == "__main__":
    raise SystemExit(main())
