_target_: planning.mpc.MPCPlanner
max_iter: 20
n_taken_actions: 5
sub_planner:
  target: planning.gd.GDPlanner
  lr: 0.1
  sample_type: zero
  action_noise: 0
  horizon: 25
  var_scale: 1
  opt_steps: 100
  eval_every: -1
adaptation:
  enabled: true
  steps: 1
  buffer_size: 5
  buffer_strategy: recent
  update_scope: predlast_enclast
  pred_lr: 5e-4
  enc_lr: 1e-5
  action_lr: 5e-4
  stop_grad: true
  grad_clip_norm: 1.0
name: mpc_gd_ada
